<?php

namespace BF13\Bundle\BusinessApplicationBundle\Repository;

use BF13\Component\DomainConnect\DomainEntityRepository;

/**
 * DataValueListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataValueListRepository extends DomainEntityRepository
{
}
