<?php

namespace BF13\Bundle\BusinessApplicationBundle\Repository;

use BF13\Component\Storage\DoctrineUnit\Repository;

/**
 * InstantMessage
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstantMessage extends Repository
{
}
