<?php

namespace BF13\Bundle\BusinessApplicationBundle\Repository;

use BF13\Component\DomainConnect\DomainEntityRepository;

/**
 * ValueListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValueListRepository extends DomainEntityRepository
{
}
