BF13\Bundle\BusinessApplicationBundle\Entity\ValueList:
    alias: vl
    properties:
        total:
          field: COUNT(vl)
        id:
            field: vl.id
        vlkey:
            field: vl.vlkey
        data:
            field: vl.data
        
    conditions: []
