BF13\Bundle\BusinessApplicationBundle\Entity\ValueList:
  type: entity
  repositoryClass: BF13\Bundle\BusinessApplicationBundle\Repository\ValueListRepository
  table: valuelist
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    vlkey:
      type: string
      unique: true
    data:
      type: array
