BF13\Bundle\BusinessApplicationBundle\Entity\ValueList:
    alias: vl
    properties:
        total:
          field: COUNT(vl)
        id:
            field: vl.id
        name:
            field: vl.name
        list_key:
            field: vl.list_key
        value:
            field: vlv.value
            joins:
              vl.DataListValues: vlv
        value_key:
            field: vlv.value_key
            joins:
              vl.DataListValues: vlv
        
    conditions: []
